server:
  port: 8010
  shutdown: graceful
  
  
spring:
  application:
    name: user-details-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    
    url: jdbc:mysql://172.17.0.2:3306/pthore
    username: root
    password: root

